// Generated by CoffeeScript 1.3.3
(function() {
  var Dialog, T,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  T = require("node-term-ui");

  Dialog = (function(_super) {

    __extends(Dialog, _super);

    function Dialog(opts) {
      var _this = this;
      Dialog.__super__.constructor.call(this, opts);
      this.botRightCorner = this.botLeftCorner = this.topRightCorner = this.topLeftCorner = T.B(3, 3, 3, 3);
      this.tabs = new T.Tabs({
        position: "bottom"
      });
      this.tabs.on("activeTab", function(option) {
        var _base;
        return typeof (_base = _this.dialogOptionHandlers)[option] === "function" ? _base[option]() : void 0;
      });
    }

    Dialog.prototype.draw = function() {
      Dialog.__super__.draw.call(this);
      this.drawOptions();
      return this;
    };

    Dialog.prototype.drawBorders = function() {
      var botY, rightX;
      Dialog.__super__.drawBorders.call(this);
      T.saveFg().fg(this.borderColor);
      T.pos(this.bounds.x - 1, this.bounds.y).out(T.B(0, 3, 3, 0)).pos(this.bounds.x - 1, this.bounds.y - 1).out(T.B(0, 3, 0, 3)).pos(this.bounds.x, this.bounds.y - 1).out(T.B(3, 0, 0, 3)).pos(this.bounds.x + 1, this.bounds.y).out(T.B(3, 3, 0, 0));
      rightX = this.bounds.x + this.bounds.w - 1;
      T.pos(rightX + 1, this.bounds.y).out(T.B(3, 0, 3, 0)).pos(rightX + 1, this.bounds.y - 1).out(T.B(3, 0, 0, 3)).pos(rightX, this.bounds.y - 1).out(T.B(0, 3, 0, 3)).pos(rightX - 1, this.bounds.y).out(T.B(3, 3, 0, 0));
      botY = this.bounds.y + this.bounds.h - 1;
      T.pos(rightX + 1, botY).out(T.B(3, 0, 0, 3)).pos(rightX + 1, botY + 1).out(T.B(3, 0, 3, 0)).pos(rightX, botY + 1).out(T.B(0, 3, 3, 0)).pos(rightX - 1, botY).out(T.B(3, 3, 0, 0));
      T.pos(this.bounds.x - 1, botY).out(T.B(0, 3, 0, 3)).pos(this.bounds.x - 1, botY + 1).out(T.B(0, 3, 3, 0)).pos(this.bounds.x, botY + 1).out(T.B(3, 0, 3, 0)).pos(this.bounds.x + 1, botY).out(T.B(3, 3, 0, 0));
      return T.restoreFg();
    };

    Dialog.prototype.setOptions = function(options) {
      var option, _i, _len;
      this.dialogOptions = options;
      this.dialogOptionHandlers = {};
      for (_i = 0, _len = options.length; _i < _len; _i++) {
        option = options[_i];
        this.dialogOptionHandlers[option[0]] = option[2];
      }
      return this.tabs.setItems(options);
    };

    Dialog.prototype.drawOptions = function() {
      this.tabs.x = this.bounds.x + this.bounds.w - this.tabs.width - 2;
      this.tabs.y = this.bounds.y + this.bounds.h - 1;
      T._d(this.bounds);
      return this.tabs.draw();
    };

    Dialog.prototype.focus = function() {
      Dialog.__super__.focus.call(this);
      return this.drawOptions();
    };

    Dialog.prototype.blur = function() {
      Dialog.__super__.blur.call(this);
      return this.drawOptions();
    };

    Dialog.prototype.hide = function() {
      Dialog.__super__.hide.call(this);
      this.tabs.hide();
      return this;
    };

    return Dialog;

  })(T.Box);

  module.exports = Dialog;

}).call(this);
