// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    start: "Shion has awoken once again. \nThis time his surroundings are both familiar and yet not.\nAfter defeating BioMeka and the Demon King shion finds himself\nwashed up on the shore of a strange island made of text.\n\nEquipped with nothing but a sword and and old pair of sneakers\nyour adventure begins!"
  };

}).call(this);
