// Generated by CoffeeScript 1.6.1
(function() {
  var Dialog, T,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  T = require("node-term-ui");

  Dialog = (function(_super) {

    __extends(Dialog, _super);

    function Dialog(opts) {
      Dialog.__super__.constructor.call(this, opts);
      this.topLeftCorner = "█";
      this.topRightCorner = T.B(3, 0, 0, 3);
      this.botLeftCorner = T.B(0, 3, 3, 0);
      this.botRightCorner = T.B(3, 0, 3, 0);
    }

    Dialog.prototype.draw = function() {
      return Dialog.__super__.draw.call(this);
    };

    return Dialog;

  })(T.Box);

  module.exports = Dialog;

}).call(this);
