// Generated by CoffeeScript 1.6.1
(function() {
  var T, centerText;

  T = require("node-term-ui");

  centerText = function(y, text) {
    return T.pos((T.width / 2) - (text.length / 2), y).out(text);
  };

  module.exports = {
    draw: function() {
      var mv;
      T.clear();
      T.hideCursor();
      mv = T.height / 2;
      centerText(mv, "wonderboy-in-ascii-world");
      return centerText(mv + 1, "press any key to start");
    }
  };

}).call(this);
